### PR TITLE
Leet PW/AdminPW

### PR DESCRIPTION
**Pull request by JacobMGEvans**

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
There will be a merge conflict now, I didn't pull whatever changes you merged from another PR

**Comment by JacobMGEvans** [comment]
Probably just spacing issue :)

**Comment by JacobMGEvans** [comment]
👍 Thank you! :)

**Comment by tarahmarie** [comment]
Please note there's an authors.txt file you may wish to add your name to now! :-)

**Pull request merged**
