### PR TITLE
Nerdbranch1

### PR DESCRIPTION
**Pull request by corewarrior**
Made some additions to nerdlist.txt, regenerated nerdlist-hashed.tsv, added my name to authors.txt, and added a shebang in  hash-nerdlist.py to deal with potential issues where multiple Python interpreters (2,3) are installed

### CODE REVIEW

**Comment by tabathad** [comment]
Heyo @corewarrior - resolve the conflicts and ping when you are ready for review!

**Comment by corewarrior** [comment]
Hey Tara. I resolve the conflicts. Want to give it another try.

**Comment by tabathad** [comment]
Looks like there is still a conflict @corewarrior - if you want to resolve it and ping me, I'll get it merged then.

**Comment by tabathad** [comment]
@corewarrior - a heads up this is still unmerged. Please fix the merge conflicts and ping me so I can add your change.

**Comment by corewarrior** [comment]
Hey Tarah! You want to give it a try now? Thanks!

**Comment by tabathad** [comment]
Tabatha here ( @tabathad ), I help maintain the repo.  Looks good - merging now!

**Pull request merged**
